---
- name: Créer le répertoire pour le monitoring
  file:
    path: /opt/telemonitor/monitoring
    state: directory
    mode: '0755'

- name: Créer le répertoire pour les données Prometheus
  file:
    path: /opt/telemonitor/monitoring/prometheus_data
    state: directory
    mode: '0755'

- name: Créer le répertoire pour les données Grafana
  file:
    path: /opt/telemonitor/monitoring/grafana_data
    state: directory
    mode: '0755'

- name: Copier la configuration Prometheus
  copy:
    src: prometheus.yml
    dest: /opt/telemonitor/monitoring/prometheus.yml
    mode: '0644'

- name: Démarrer Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - /opt/telemonitor/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/telemonitor/monitoring/prometheus_data:/prometheus
    restart_policy: always

- name: Démarrer Grafana
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /opt/telemonitor/monitoring/grafana_data:/var/lib/grafana
      - /opt/telemonitor/simulator/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart_policy: always