version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - telemonitor

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ../simulator/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - telemonitor