global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'telecom-simulator'
    static_configs:
      - targets: ['telecom-simulator:8000']
        labels:
          service: 'telecom-simulator'

  - job_name: 'diameter-exporter'
    static_configs:
      - targets: ['diameter-exporter:9111']
        labels:
          service: 'diameter'

  - job_name: 'voip-exporter'
    static_configs:
      - targets: ['voip-exporter:9010']
        labels:
          service: 'voip'